drop table if exists PersonsFind2 ;
create table PersonsFind2(
  id int primary key auto_increment,
  Id_Person int comment 'Идентификатор персоны.',
  Resident int comment 'Признак резидентности. 1- резидент, 0 –не резидент.',
  PersonCodeU varchar(255) comment 'GUID код персоны.',
  Birthday dateTime comment 'Дата рождения',
  Id_PersonName int comment 'Идентификатор имен персоны',
  LastName varchar(255) comment 'Фамилия персоны',
  FirstName varchar(255) comment 'Имя персоны',
  MiddleName varchar(255) comment 'Отчество персоны',
  PersonNameDateBegin dateTime comment 'Дата начала действия записи',
  PersonNameDateEnd dateTime comment 'Дата окончания действия записи',
  FIO varchar(255) comment 'ФИО персоны',
  PasportSeries varchar(255) comment 'Серия паспорта',
  PasportNumber varchar(255) comment 'Номер паспорта',
  PasportDate varchar(255) comment 'Дата выдачи паспорта',
  PasportIssued varchar(255) comment 'Кем выдан паспорт',
  AtestatSeries varchar(255) comment 'Серия аттестата',
  AtestatNumber varchar(255) comment 'Номер аттестата',
  AtestatDate varchar(255) comment 'Дата выдачи аттестата',
  Id_PersonSex int comment 'Идентификатор пола персоны',
  PersonSexName varchar(255) comment 'Название пола персоны',
  Id_Language int comment 'Идентификатор языка названий',
  Id_PersonDocumentPasp int comment 'Идентификатор Id_PersonDocument документа из  набора PersonDocuments для паспорта',
  Id_PersonDocumentAtestat int comment 'Идентификатор Id_PersonDocument документа из  набора PersonDocuments для аттестата',
  Id_PersonTypeDict int comment 'Идентификатор типа персоны',
  PersonTypeName varchar(255) comment 'Название типа персоны',
  Father varchar(255) comment 'Отец',
  Mother varchar(255) comment 'Мать',
  FatherPhones varchar(255) comment 'Телефоны отца',
  MotherPhones varchar(255) comment 'Телефоны матери',
  Birthplace varchar(255) comment 'Место рождения',
  LanguagesAreStudied varchar(255) comment 'Какие иностранные языки узачались',
  LastNameEn varchar(255) comment 'Фамилия на английском (добавлено в версии 2)',
  FirstNameEn varchar(255) comment 'Имя на английском (добавлено в версии 2)',
  MiddleNameEn varchar(255) comment 'Отчество на английском (добавлено в версии 2)',
  FIOEn varchar(255) comment 'ФИО на английском (добавлено в версии 2)'
);
insert into PersonsFind2 (
Id_PersonTypeDict,
MotherPhones,
AtestatSeries,
FIOEn,
Id_Person,
Id_Language,
LanguagesAreStudied,
Father,
LastName,
AtestatDate,
Birthplace,
Id_PersonSex,
Birthday,
Resident,
LastNameEn,
FirstName,
Id_PersonDocumentAtestat,
FIO,
PersonNameDateBegin,
PersonCodeU,
Id_PersonName,
PasportNumber,
PersonNameDateEnd,
PersonSexName,
MiddleNameEn,
FirstNameEn,
MiddleName,
AtestatNumber,
PasportDate,
Mother,
PasportSeries,
PasportIssued,
FatherPhones,
PersonTypeName,
Id_PersonDocumentPasp
)
 values 
(
'1',
'',
'',
'',
'711613',
'1',
'',
'',
'Синєпольський',
'0001-01-01T00:00:00',
'',
'1',
'1991-09-15T00:00:00',
'1',
'',
'Ігор',
'0',
'Синєпольський Ігор Володимирович',
'1991-09-15T00:00:00',
'2045c6bb-823c-472d-95a7-ca19dd1f94e2',
'708191',
'068119',
'2099-12-31T23:59:59',
'Чоловіча',
'',
'',
'Володимирович',
'',
'2007-12-22T00:00:00',
'',
'CЮ',
'Кам`янсько - Дніпровським РВ УМВС України в Запорізькій області',
'',
'Абітуріент',
'1616282'
);
